version: '3'

services:
  api:
    build:
      Isitar.DoenerOrder.Api
    ports:
    - 16080:80
    environment:
      "ConnectionStrings:DefaultConnection": "User ID=doenerOrderUser;Password=doenerOrderPass;Server=db;Port=5432;Database=doenerorder;Integrated Security=true;Pooling=true;"
      
  db:
    image: postgres
    environment:
      POSTGRES_USER: doenerOrderUser
      POSTGRES_PASSWORD: doenerOrderPass
    volumes:
      - productservice-db:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  productservice-db: {}